"""empty message

Revision ID: f126651d4866
Revises: c00ff7978fec
Create Date: 2023-10-29 00:44:20.777966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f126651d4866'
down_revision: Union[str, None] = 'c00ff7978fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validatormodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validatormodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('validator_id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['validator_id'], ['validator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
